# Generated by Django 4.1.6 on 2023-03-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_customer_order_orderitem_mpesatransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
